CREATE TABLE user_credentials(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_Id BIGINT NOT NULL,
    user_name VARCHAR(255) NOT NULL UNIQUE,
    psswd VARCHAR(255) NOT NULL,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_Id) REFERENCES users(user_id) ON DELETE CASCADE
);