CREATE TABLE  admin(
    admin_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    names VARCHAR (50) NOT NULL ,
    paternal_surname VARCHAR(50) NOT NULL ,
    maternal_surname VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    modification_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);