CREATE TABLE admin_credentials (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
admin_Id BIGINT NOT NULL,
admin_name VARCHAR(255) NOT NULL,
psswd VARCHAR(255) NOT NULL,
creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (admin_Id) REFERENCES admin(admin_id) ON DELETE CASCADE
);
